### ISSUE TITLE
Implement centered grid sampling for objects of various size.

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-wako-searchfirst#48]
When acquiring objects that vary a lot in size (e.g., small objects fit in a single field of view, large objects require 3x2 tiles in second pass acquisition), we'd like to have a sampling that records:
* the object center for objects that fit into a single FOV,
* the centers of grid tiles (with definable overlap) centered on each object, for objects larger than a single FOV.

@nrepina what should be the behavior if two objects are close to each other? If we just sample per-object, we have the possibility of overlap (and therefore bleaching) between tiles belonging to two different objects.

**Comment by imagejan** [comment]
Here's a toy sample image for further discussion:

![image](https://github.com/fmi-faim/faim-wako-searchfirst/assets/2033938/29e11525-5890-454e-a33d-9d53bafddcca)

**Comment by nrepina** [comment]
Thank you @imagejan ! For the case there two (or more) objects are close to each other, I think that for the first implementation it makes sense to discard the overlapping objects entirely to avoid bleaching. 
If the objects are like in the toy sample image, priority should be given to keep the one that fits into a single FoV (i.e. top-left organoid). The larger organoid next to it would then be discarded and not be imaged at all. 
In the case where all organoids are large, the one that is discarded is arbitrary, e.g. first one in imaging order is kept, and the subsequent overlapping ones are discarded. Does that make sense?
